In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load Cleaned Dataset

In [2]:
cleaned_df = pd.read_csv("../Fitbit/data/fitbit_cleaned.csv")
cleaned_df.head()

,Age,Gender,Weight,Height,Max_BPM,Avg_BPM,Resting_BPM,Session_Duration,Fat_Percentage,Water_Intake,...,Experience_Level,BMI,Base_MET,HR_Intensity,Effective_MET,Calories_Burned,Workout_Type_HIIT,Workout_Type_Mixed,Workout_Type_Strength,Workout_Type_Yoga
0,56,0,53.8,1.62,163.0,149.0,71.0,1.01,22.1,3.5,...,1,20.4,9.5,0.847826,8.054348,437.7,1,0,0,0
1,46,1,54.9,1.75,170.0,126.0,73.0,0.25,19.9,3.4,...,0,18.0,3.0,0.546392,1.639175,22.5,0,0,0,1
2,32,0,68.5,1.61,190.0,171.0,60.0,0.33,20.4,2.7,...,1,26.5,9.5,0.853846,8.111538,183.4,1,0,0,0
3,25,1,98.8,1.86,189.0,135.0,69.0,0.78,30.3,4.4,...,0,28.5,3.0,0.550000,1.650000,127.2,0,0,0,1
4,38,1,95.5,1.71,176.0,138.0,66.0,0.55,23.7,2.2,...,0,32.5,7.0,0.654545,4.581818,240.7,0,0,0,0

In [3]:
cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14102 entries, 0 to 14101
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    14102 non-null  int64
 1   Gender                 14102 non-null  int64
 2   Weight                 14102 non-null  float64
 3   Height                 14102 non-null  float64
 4   Max_BPM                14102 non-null  float64
 5   Avg_BPM                14102 non-null  float64
 6   Resting_BPM            14102 non-null  float64
 7   Session_Duration       14102 non-null  float64
 8   Fat_Percentage         14102 non-null  float64
 9   Water_Intake           14102 non-null  float64
 10  Workout_Frequency      14102 non-null  int64
 11  Experience_Level       14102 non-null  int64
 12  BMI                    14102 non-null  float64
 13  Base_MET               14102 non-null  float64
 14  HR_Intensity           14102 non-null  float64
 15  Effective_MET          14102 non-null  float64
 16  Calories_Burned        14102 non-null  float64
 17  Workout_Type_HIIT      14102 non-null  int64
 18  Workout_Type_Mixed     14102 non-null  int64
 19  Workout_Type_Strength  14102 non-null  int64
 20  Workout_Type_Yoga      14102 non-null  int64
dtypes: float64(13), int64(8)
memory usage: 2.3 MB

# Train_Test_Split

In [4]:
X = cleaned_df.drop('Calories_Burned', axis = 1)
Y = cleaned_df['Calories_Burned']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42
)

## Fit and Transform the Data

In [6]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()

# The scaler calculates the mean and standard deviation for each feature using fit()
X_train_scaled = scaler.fit_transform(X_train)

# Each training value is converted to its standardized value using transform()
X_test_scaled = scaler.transform(X_test)

# converting it to Dataframe
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

X_train_scaled.tail()

,Age,Gender,Weight,Height,Max_BPM,Avg_BPM,Resting_BPM,Session_Duration,Fat_Percentage,Water_Intake,Workout_Frequency,Experience_Level,BMI,Base_MET,HR_Intensity,Effective_MET,Workout_Type_HIIT,Workout_Type_Mixed,Workout_Type_Strength,Workout_Type_Yoga
5191,0.046727,0.994607,1.205662,0.101576,-0.197919,1.018534,0.375692,-0.065969,0.286991,-0.325425,-1.300654,-1.086818,1.471739,1.269024,1.479529,1.480256,1.957890,-0.501357,-0.504677,-0.494287
13418,0.214284,0.994607,1.508719,0.101576,-0.431769,-1.306245,0.375692,-0.623137,0.856373,0.318885,-1.300654,-1.086818,1.843125,-1.708532,-1.533798,-1.544616,-0.510754,-0.501357,-0.504677,2.023117
5390,-1.377501,-1.005422,-0.741478,1.232446,1.750830,1.428789,-0.470449,0.943896,-0.399617,1.285350,-0.693668,-0.137357,-1.605454,0.581896,0.442265,0.489190,-0.510754,1.994587,-0.504677,-0.494287
860,-1.293723,-1.005422,0.266186,-0.720875,0.503631,0.539903,-1.457614,1.152834,-1.169958,1.929660,0.520305,0.812105,0.994244,0.581896,0.497682,0.510102,-0.510754,1.994587,-0.504677,-0.494287
7270,-1.042388,0.994607,2.463348,2.054897,0.971331,0.266400,-2.021708,-0.205261,-2.074271,0.318885,1.127291,0.812105,1.153409,-0.334275,-0.041388,-0.349363,-0.510754,-0.501357,1.981464,-0.494287

# Helper function for Model Evaluation

In [20]:
import numpy as np

def eval_model(model, x_train, y_train, x_test, y_test, model_name):
    model.fit(x_train, y_train)
    y_predict = model.predict(x_test)

    # Model Evaluation
    mae = mean_absolute_error(y_test, y_predict)
    rmse = np.sqrt(mean_squared_error(y_test, y_predict))
    r2 = r2_score(y_test, y_predict)

    print(f"{model_name}")
    print("-" * 35)
    print(f"MAE  : {mae:.4f}")
    print(f"RMSE : {rmse:.4f}")
    print(f"R² Score : {r2:.4f}")

# Linear Regression

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

lr_model = LinearRegression()

eval_model(lr_model, X_train, Y_train, X_test, Y_test, "Linear Regression")

Linear Regression
-----------------------------------
MAE  : 31.7615
RMSE : 45.7187
R² Score : 0.9263

# Ridge Regression

In [30]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)

eval_model(ridge_model, X_train, Y_train, X_test, Y_test, "Ridge Regression")

Ridge Regression
-----------------------------------
MAE  : 31.7545
RMSE : 45.7096
R² Score : 0.9263

# Random Forest

In [23]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

eval_model(rf_model, X_train, Y_train, X_test, Y_test, "Random Forest")

Random Forest
-----------------------------------
MAE  : 3.6305
RMSE : 7.0579
R² Score : 0.9982

# KNN Regressor

In [35]:
from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor(n_neighbors=5)

eval_model(knn_model, X_train_scaled, Y_train, X_test_scaled, Y_test, "KNN Regressor")

KNN Regressor
-----------------------------------
MAE  : 28.2483
RMSE : 39.2907
R² Score : 0.9455

# Decision Tree

In [41]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor()

print("Unscaled Data")
eval_model(dt_model, X_train, Y_train, X_test, Y_test, "Decision Tree")

print("-"*30)
print("Scaled Data")
eval_model(dt_model, X_train_scaled, Y_train, X_test_scaled, Y_test, "Decision Tree")

Unscaled Data
Decision Tree
-----------------------------------
MAE  : 7.5911
RMSE : 11.8889
R² Score : 0.9950
------------------------------
Scaled Data
Decision Tree
-----------------------------------
MAE  : 7.5820
RMSE : 11.9946
R² Score : 0.9949

# SVR

In [42]:
from sklearn.svm import SVR

svr_model = SVR()

print("Unscaled Data")
eval_model(svr_model, X_train, Y_train, X_test, Y_test, "Support Vector Regression")

print("-"*30)
print("Scaled Data")
eval_model(svr_model, X_train_scaled, Y_train, X_test_scaled, Y_test, "Support Vector Regression")

Unscaled Data
Support Vector Regression
-----------------------------------
MAE  : 115.9074
RMSE : 148.9751
R² Score : 0.2170
------------------------------
Scaled Data
Support Vector Regression
-----------------------------------
MAE  : 28.0343
RMSE : 48.2407
R² Score : 0.9179

# XGBoost Regressor

In [44]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in C:\Users\rishi\miniconda3\envs\ds-env\Lib\site-packages (from xgboost) (2.4.3)
Requirement already satisfied: scipy in C:\Users\rishi\miniconda3\envs\ds-env\Lib\site-packages (from xgboost) (1.18.0)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   - -------------------------------------- 2.4/69.5 MB 22.3 MB/s eta 0:00:04
   -- ------------------------------------- 4.5/69.5 MB 12.8 MB/s eta 0:00:06
   --- ------------------------------------ 5.5/69.5 MB 10.8 MB/s eta 0:00:06
   --- ------------------------------------ 6.6/69.5 MB 8.8 MB/s eta 0:00:08
   ---- ----------------------------------- 7.3/69.5 MB 7.6 MB/s eta 0:00:09
   ---- ----------------------------------- 7.6/69.5 MB 6.7 MB/s eta 0:00:10
   ---- ----------------------------------- 7.9/69.5 MB 5.9 MB/s eta 0:00:11
   ---- ----------------------------------- 8.1/69.5 MB 5.4 MB/s eta 0:00:12
   ---- ----------------------------------- 8.7/69.5 MB 4.7 MB/s eta 0:00:13
   ----- ---------------------------------- 8.9/69.5 MB 4.5 MB/s eta 0:00:14
   ----- ---------------------------------- 9.4/69.5 MB 4.2 MB/s eta 0:00:15
   ----- ---------------------------------- 10.0/69.5 MB 4.0 MB/s eta 0:00:15
   ------ --------------------------------- 10.5/69.5 MB 3.9 MB/s eta 0:00:16
   ------ --------------------------------- 11.0/69.5 MB 3.8 MB/s eta 0:00:16
   ------ --------------------------------- 11.5/69.5 MB 3.8 MB/s eta 0:00:16
   ------- -------------------------------- 12.3/69.5 MB 3.7 MB/s eta 0:00:16
   ------- -------------------------------- 13.1/69.5 MB 3.7 MB/s eta 0:00:16
   ------- -------------------------------- 13.9/69.5 MB 3.7 MB/s eta 0:00:16
   -------- ------------------------------- 14.7/69.5 MB 3.7 MB/s eta 0:00:15
   -------- ------------------------------- 15.5/69.5 MB 3.7 MB/s eta 0:00:15
   --------- ------------------------------ 16.5/69.5 MB 3.8 MB/s eta 0:00:15
   ---------- ----------------------------- 17.6/69.5 MB 3.8 MB/s eta 0:00:14
   ---------- ----------------------------- 18.6/69.5 MB 3.9 MB/s eta 0:00:14
   ----------- ---------------------------- 19.7/69.5 MB 3.9 MB/s eta 0:00:13
   ------------ --------------------------- 21.0/69.5 MB 4.0 MB/s eta 0:00:13
   ------------ --------------------------- 22.0/69.5 MB 4.0 MB/s eta 0:00:12
   ------------- -------------------------- 23.3/69.5 MB 4.1 MB/s eta 0:00:12
   -------------- ------------------------- 24.6/69.5 MB 4.2 MB/s eta 0:00:11
   -------------- ------------------------- 26.0/69.5 MB 4.3 MB/s eta 0:00:11
   --------------- ------------------------ 27.3/69.5 MB 4.4 MB/s eta 0:00:10
   ---------------- ----------------------- 28.6/69.5 MB 4.4 MB/s eta 0:00:10
   ---------------- ----------------------- 29.4/69.5 MB 4.4 MB/s eta 0:00:10
   ----------------- ---------------------- 29.6/69.5 MB 4.4 MB/s eta 0:00:10
   ----------------- ---------------------- 30.1/69.5 MB 4.3 MB/s eta 0:00:10
   ----------------- ---------------------- 30.9/69.5 MB 4.2 MB/s eta 0:00:10
   ------------------ --------------------- 31.5/69.5 MB 4.2 MB/s eta 0:00:10
   ------------------ --------------------- 32.0/69.5 MB 4.2 MB/s eta 0:00:10
   ------------------ --------------------- 32.8/69.5 MB 4.1 MB/s eta 0:00:09
   ------------------- -------------------- 33.6/69.5 MB 4.1 MB/s eta 0:00:09
   ------------------- -------------------- 34.6/69.5 MB 4.1 MB/s eta 0:00:09
   -------------------- ------------------- 35.4/69.5 MB 4.1 MB/s eta 0:00:09
   -------------------- ------------------- 36.4/69.5 MB 4.1 MB/s eta 0:00:08
   --------------------- ------------------ 37.5/69.5 MB 4.2 MB/s eta 0:00:08
   ---------------------- ----------------- 38.5/69.5 MB 4.2 MB/s eta 0:00:08
   ---------------------- ----------------- 39.6/69.5 MB 4.2 MB/s eta 0:00:08
   ----------------------- ---------------- 40.4/69.5 MB 4.2 MB/s eta 0:00:07
   ----------------------- ---------------- 41.7/69.5 MB 4.2 MB/s eta 0:00:07
   ------------------------ --------------- 43.0/69.5 MB 4.3 MB/s eta 0:00:07
   ------------------------- -------------- 44.3/69.5 MB 4.3 MB/s eta 0:00:06
   -------------------------- ------------- 45.9/69.5 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 47.2/69.5 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 48.5/69.5 MB 4.4 MB/s eta 0:00:05
   ---------------------------- ----------- 49.0/69.5 MB 4.4 MB/s eta 0:00:05
   ---------------------------- ----------- 49.8/69.5 MB 4.4 MB/s eta 0:00:05
   ----------------------------- ---------- 50.9/69.5 MB 4.4 MB/s eta 0:00:05
   ----------------------------- ---------- 51.6/69.5 MB 4.4 MB/s eta 0:00:05
   ------------------------------ --------- 52.7/69.5 MB 4.4 MB/s eta 0:00:04
   ------------------------------ --------- 53.5/69.5 MB 4.4 MB/s eta 0:00:04
   ------------------------------- -------- 54.5/69.5 MB 4.4 MB/s eta 0:00:04
   ------------------------------- -------- 55.6/69.5 MB 4.4 MB/s eta 0:00:04
   -------------------------------- ------- 56.9/69.5 MB 4.4 MB/s eta 0:00:03
   --------------------------------- ------ 57.9/69.5 MB 4.4 MB/s eta 0:00:03
   ---------------------------------- ----- 59.5/69.5 MB 4.5 MB/s eta 0:00:03
   ---------------------------------- ----- 60.3/69.5 MB 4.5 MB/s eta 0:00:03
   ----------------------------------- ---- 61.3/69.5 MB 4.5 MB/s eta 0:00:02
   ----------------------------------- ---- 62.4/69.5 MB 4.5 MB/s eta 0:00:02
   ------------------------------------ --- 63.2/69.5 MB 4.5 MB/s eta 0:00:02
   ------------------------------------ --- 63.7/69.5 MB 4.5 MB/s eta 0:00:02
   ------------------------------------ --- 64.2/69.5 MB 4.4 MB/s eta 0:00:02
   ------------------------------------- -- 64.7/69.5 MB 4.4 MB/s eta 0:00:02
   ------------------------------------- -- 65.5/69.5 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 66.1/69.5 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 66.8/69.5 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 67.6/69.5 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  68.4/69.5 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  69.2/69.5 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 4.2 MB/s  0:00:16
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

In [45]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=50,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

print("Unscaled Data")
eval_model(xgb_model, X_train, Y_train, X_test, Y_test, "XGBoost Regression")

print("-"*30)
print("Scaled Data")
eval_model(xgb_model, X_train_scaled, Y_train, X_test_scaled, Y_test, "XGBoost Regression")

Unscaled Data
XGBoost Regression
-----------------------------------
MAE  : 3.6159
RMSE : 6.0260
R² Score : 0.9987
------------------------------
Scaled Data
XGBoost Regression
-----------------------------------
MAE  : 3.6159
RMSE : 6.0260
R² Score : 0.9987